#!/bin/sh

format=$(cat pack.mcmeta | grep pack_format | tr -cs '0-9' ' ' | cut -d' ' -f2) ; echo "format$format"
version=$(cat pack.mcmeta | grep description | cut -d'.' -f2 | tr -cs '0-9' ' ') ; echo "version $version"
newVersion=$(($version+1))

sed -i -e "s/\.[0-9]*/.$newVersion/" pack.mcmeta

git add pack.mcmeta
git rm SummerFields*
git commit -m "delete deploy"

git archive master -o "SummerFields_rp$format.zip"
git add "SummerFields_rp$format.zip"
git commit -m "add deploy"
